apiVersion: v1
kind: Pod
metadata:
  name: druid-pod
  namespace: insight
  labels:
    name: druid-pod
    context: insight
spec:
  containers:
    -
      name: druid
      image: deskefa/druid-minikube:2.5.8
      imagePullPolicy: IfNotPresent
      ports:
        -
          containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: druid-service
  namespace: insight
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 9095
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: druid-pod
    context: insight
